name: Update Helm values.yaml with new image tag

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Helm app folder to update (e.g. app or app2)'
        required: true
      new_image_tag:
        description: 'New Docker image tag to set in values.yaml'
        required: true

jobs:
  update-values:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "APP_FOLDER=${{ inputs.app_name }}" >> $GITHUB_ENV
          echo "VALUES_FILE=${{ inputs.app_name }}/values.yaml" >> $GITHUB_ENV

      - name: Show existing values.yaml
        run: cat $VALUES_FILE

      - name: Update image tag in values.yaml
        run: |
          sed -i 's|tag:.*|tag: "${{ inputs.new_image_tag }}"|' "$VALUES_FILE"
          echo "Updated image tag in $VALUES_FILE"
          cat $VALUES_FILE

      - name: Commit changes
        run: |
          git config user.name "Vipul"
          git config user.email "vipul81kumar@gmail.com"
          git add $VALUES_FILE
          git commit -m "chore: bump image tag for $APP_FOLDER to ${{ inputs.new_image_tag }}"
          git push
